name = "FluidFields"
uuid = "390a1fbe-c11f-11e8-0e71-0f874e7fb199"
authors = ["Felipe Alves <favbalves@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FluidTensors = "9c362f20-be79-11e8-0b20-338637273ba1"
InplaceRealFFT = "370c16e2-4e51-11e9-3235-e391f9c4d929"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
